apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres-svc
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: postgres 
    spec:
      terminationGracePeriodSeconds: 10 # tempo para o container encerrar 
      containers:
      - name: postgresql
        image: postgres:17.0
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        env:
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: dados
                key: DATABASE_NAME     
                
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: senhas
                key: DATABASE_PASSWORD              
      volumes:
        - name:
          persistentVolumeClaim:
            claimName: postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-hostpath-sc # Container storage Interface. Abstração de armazenamento
